name: Daily Action at 10:22 PM IST

on:
  workflow_dispatch:
  schedule:
    - cron: '38 22 * * *'  # 4:52 PM UTC corresponds to 10:22 PM IST

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "This action runs every day at 10:22 PM IST!"
