name: Daily Action at 9 PM IST
 
on:
  schedule:
    - cron: '05 22 * * *'  # This is in UTC, so it's 9 PM IST (India/Kolkata)
 
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "This action runs every day at 9 PM IST!"
