name: dockerbuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  LogintodockerhubDEV:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
       username: ${{secrets.DOCKERHUBUSERNAME}}
       password: ${{secrets.DOCKERHUBPASSWORD}}
    - name: Docker Build
      run: docker build -t sampledocker .
    - name: Docker Tag
      run: docker tag sampledocker dockerakhila/sampledocker
    - name: Docker Push
      run: docker push dockerakhila/sampledocker
